### PR TITLE
Add Secret Create/Update/Delete functionality

### PR DESCRIPTION
**Pull request by texnewmex**
cc @amigus @cujaf6 @timothyfield

### CODE REVIEW

**Comment by amigus** [comment]
Thanks for the contributions, Timothy!  Note that I used JSON patching in dsv-k8s/pkg/injector/injector.go for reference.

**Comment by texnewmex** [comment]
Is there a something blocking this from being merged?  This PR is holding us up.

**Comment by amigus** [comment]
> Is there something blocking this from being merged? This PR is holding us up.

Sorry, I assumed you were just using your fork so the status of the PR didn't affect your deployment.

I accepted one change but requested changes on the other.  The plan for update functionality was/is to use github.com/mattbaird/jsonpatch so I wanted to give you the opportunity to do that if you are up for it.

If you'd rather I do it then I was thinking I'd accept your change as 1.0.2 then I can make the changes to use jsonpatch and release that as 1.1.0.

LMK how you'd like to proceed and thanks again for your contribution!

**Comment by timothyfield** [comment]
Hi @amigus , 

Regarding using jsonpatch, this would require accepting a jsonpatch argument to the update function and update the struct locally, before sending to request to DSV? Because looking at the API documentation for DSV, it doesn't look like it would accept a jsonpatch request directly.

I saw the jsonpatch implementation in dsv-k8s, but I thought that was because mutating admission controller webhooks in Kubernetes require updates to be in a jsonpatch format.

**Comment by texnewmex** [comment]
Hi all we are still having to maintain a fork of this repo.  Will you please merge this?  It has been over a year now.

**Pull request closed without merging**
